services:
  - type: web
    name: metabase-dashboard
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MB_DB_TYPE
        value: h2
      - key: MB_DB_FILE
        value: ./metabase.db
      - key: MB_ENCRYPTION_SECRET_KEY
        value: 12345678901234567890123456789012
